[project]
name = "smart-fusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fusion-api",
    "fusion-core",
]

[tool.uv.workspace]
members = [
    "packages/fusion-core",
    "packages/fusion-api",
    "packages/fusion-datasets",
]

[tool.uv.sources]
fusion-api = { workspace = true }
fusion-core = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
